Scan POMs and JARs for license information
project-ncl/build-finder pull request #1032
Opened 2024-04-26 15:36 UTC by dwalluck

2024-04-30 13:55 UTC, vibe13 requested changes
Hi @dwalluck thanks a lot for this massive work! I have put some comments around, mostly because I missed some explanation to understand some method and it took some time to figure it all out. I have run an analysis on a big repo (jboss-eap-7.4.15.GA-CR1-maven-repository), and checked a few licenses. They mostly make sense but in some cases some GAVs are reported as missing license information, but looking at their POMs, the license seems ok to be picked. I will give you details privately so you can debug yourself.
Lastly, I still fail to see logs in the console when executing the jar :-/.

Thanks!

2024-04-30 19:20 UTC, dwalluck commented on core/src/main/java/org/jboss/pnc/build/finder/core/DistributionAnalyzer.java
> +                if (optLicenseId.isEmpty()) {
This increases the number of `if` checks, but I just moved Build Finder to Java 11 and discovered `Optional::or` from Java 9+, so I can use this I think:

```java
Optional<String> optLicenseId = LicenseUtils.findMatchingLicense(name, url)
                        .or(() -> LicenseUtils.findLicenseMapping(mapping, url))
                        .or(() -> LicenseUtils.findLicenseMapping(mapping, name));
```

2024-04-30 20:48 UTC, dwalluck commented on core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java
> +    private static Map<String, SpdxListedLicense> getLicenseIdMap() {
What's annoying is that the official SPDX Java API stores a map internally, but only returns a list (`map.values()`) in the public API.

2024-05-02 10:08 UTC, vibe13 commented on core/src/main/java/org/jboss/pnc/build/finder/core/DistributionAnalyzer.java
> +                if (optLicenseId.isEmpty()) {
nice!

2024-05-02 12:07 UTC, vibe13 commented on core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java
> +    private static Map<String, SpdxListedLicense> getLicenseIdMap() {
oh yes that would have been handy. but one initialization is better now, thanks!

2024-05-02 15:30 UTC, vibe13 approved these changes
Massive work David, thanks a lot!!

2024-05-02 16:29 UTC, merged